### ISSUE TITLE
Spendkey in Settings gives error

### ISSUE THREAD

**Issue by medolino2009** [XzenTorXz/ElectroneumGUIWallet#3]
Great job with this wallet...i love it... i see that Spendkey in Settings page gives error... Best regards. Miki

**Comment by XzenTorXz** [comment]
yes the electroneum team released a update to fix the issue, so it should be fixed by updating the electroneums binaries.

**Comment by ghost** [comment]
latest release version still has the spend key error.

**Comment by XzenTorXz** [comment]
yes im waiting for the electroneum team to publish a new Release here: https://github.com/electroneum/electroneum/releases

They allready fixed the bug: https://github.com/electroneum/electroneum/commit/7cd8effa916a42b3c797721b71f6bb63163e5499

I dont want to swap the original binaries with some self compiled, because it would look fishy. But you could build the binaries of the electroneum team by yourself and replace them in /Resources/bin
